EAC 573 S08 - Python coding in *COLAB*

Libraries, Modules and Packages

Packages
---
Module

.py


Package

directory (__init__.py),

*.py


Library

Collection of core modules

Python Library Reference

Python Core

check, Rossum 2016 (Chapters 10 & 11)




Python Package Index

Over 100k packages

Easy to browse

Easy to install (pip)

$pip install <>


In [6]:
! pip install googlefinance


  Created wheel for googlefinance: filename=googlefinance-0.7-py3-none-any.whl size=2583 sha256=7a88c267089dcc5b4b1acd362696c84cb0ab304bbe29e2929e1de4bffca4766b
  Stored in directory: /root/.cache/pip/wheels/50/bd/64/b32b38aebd40e333f615ae9e28003e88d5629e377e4f4a8a00
Successfully built googlefinance


In [58]:
#import googlefinance
#a=googlefinance.getQuotes('AAPL') 


Python Package Index (PyPI)

In [18]:
# LPBProgram15.py
from datetime import date
now = date.today()
print(now)
birthday = date(1977,7,7)
age = now - birthday
print(age)
print(age.days)

2021-10-27
16183 days, 0:00:00
16183


In [21]:
# LPBProgram16.py
import time
a = time.time()
print(time.ctime())
b=time.time()
print(time.ctime())
print(b-a)

Wed Oct 27 18:54:33 2021
Wed Oct 27 18:54:33 2021
0.0014946460723876953


In [32]:
# LPBProgram17.py
import random
fruit = random.choice(["apple", "pear", "banana"])
print(fruit)
print(random.sample(range(100,10),0))
print(random.random())
print(random.randrange(7))

apple
[]
0.9648478210061261
6


In [33]:
#LPBProgram18.py
from math import e, pi, exp, pow
print(e)
print(pi)
print(exp(3))
print(pow(2,3))

2.718281828459045
3.141592653589793
20.085536923187668
8.0


In [40]:
#LPBProgram19.py
import urllib
response = urllib.request.urlopen("http://www.google.com")
#print(response.info())
html=response.read()
print(html)

b'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world\'s information, including webpages, images, videos and more. Google has many special features to help you find exactly what you\'re looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="8qqv2ksR4lkY6Pgyo2PoIw==">(function(){window.google={kEI:\'RaZ5YbPfGZPdtQaBm4Mw\',kEXPI:\'0,1302477,59,56873,6059,206,4804,2316,383,246,5,1354,4936,314,1122516,1197762,450,189,328866,51224,16114,17444,11240,893,16679,4859,996,365,283,9007,3022,17587,4020,978,13228,3847,4192,6430,1142,13621,7059,919,5081,1593,1279,2212,241,289,149,1103,840,1983,214,4100,3514,606,2023,2297,14670,3227,2845,8,5598,6755,5096,14396,1372,552,908,2,941,2614,12710,432,3,346,1244,1,5444,149,11323,991,16

ScyPy

NumPy


VERY FAST!!!

Numeric Operations

Array / Matrix

Scalar

# optimized C ou Fortran

In [48]:
# LPBProgram20.py
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim)
x=np.zeros(5)
y = np.zeros(6)
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]


In [53]:
# LPBProgram21.py
import numpy as np
invest = [12.4, 9.8, 3.2, 11.5, 8.7]
cpi = 4.7
INV = np.array(invest)
print(INV)
print(((INV/100+1)/(cpi/100+1)-1)*100)

[12.4  9.8  3.2 11.5  8.7]
[ 7.35434575  4.87106017 -1.43266476  6.4947469   3.82043935]


In [57]:
# NUMPY FINANCIAL FUNCTIONS
# LPBProgram22.py
import numpy
print(numpy.fv(0.05, 5, -1000, 0))


5525.631250000007


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: numpy.fv is deprecated and will be removed from NumPy 1.20. Use numpy_financial.fv instead (https://pypi.org/project/numpy-financial/).
  after removing the cwd from sys.path.


-Program-Exercise 25 (pe25.py)

Calculate the standard cost of ICE CREAM WOW, assuming this standard cost card (variable costs only)

[Please: compute the performance in secs]

Base mix IC-2, 4 lbs., $1.87/lbs

Flavour 123c, 25g, $0.72/g

Grade A Milk, .89 gal., $ 3.29/gal.

Mix-In Ingredient 53, 23 oz., $0.15/oz.

Mix-In Ingredient 87, 16 oz., $0.09/oz. 


-Program-Exercise 26 (pe26.py)

Compute the accounts receivable aging (individual) and the overall average age, according to data in file “ARaging.csv":

[Please: compute the performance in secs]

File contains: Customer, Due Date, Amount


-Program-Exercise 27 (pe27.py)

Compute new amount (with interest, as of today) of accounts receivable and the total amount (with interest, as of today), according to data in file “ARaging.csv” and assuming an interest rate of 7% APR (year-based):

[Please: compute the performance in secs]

File contains: Customer, Due Date, Amount